---
title: "Second Round Reviews"
author: "Juliano Palacios Abrantes"
date: "17/05/2020"
output: pdf_document
bibliography: ../../../../References/Oceans_Canada_Biblio.bib
---

-----------------------------------------------------
Recommendation Submitted by: David VanderZwaag
-----------------------------------------------------


The authors have now responded to my last comments and most importantly
they have largely clarified the relationship of NAFO and 
Canada-USA fisheries management in the Gulf of Maine. Just three
additional comments:

1. Line 23...United Nations Law of the Sea Convention...not Seas
- Corrected in text

2. Lines 118-120...the authors might refer to more recent TRAC proposals
(2018, 2019) and it might be useful to show how the distributions 
have actually varied.from 2010-2019. 

- We changed the text to included the quota average from 2010 to 2020 (rather than an specific year) and included a table with the historic TRAC proposals from the same time period, plus a four-years historic average of before the weighted method implementation (2006 to 2009) It now reads:

*Since its introduction, the average quota allocation for each species proposed by the GoMA has been; Atlantic cod 77% Canada and 23% US, haddock 55% Canada and 45% US, and yellowtail flounder 34% Canada and 66% US [Table 1, @TRAC:2015wj; @TRAC:2015vp; @TRAC:2015tt; @TRAC:2018tw; @TRAC:2018tj; @TRAC:2018wx; @Trinko:2019ou]. However, because this is an unofficial agreement, Canada and the US ultimately take single management decisions [@Soboil:2006gw].*

3. Lines 95 and 161...the term NAFO regulatory areas should be replaced
with NAFO divisional zones. This is more accurate as the NAFO
Regulatory Area is the high seas area where NAFO actually does
regulate.

- Corrected in text
