---
title: "Second Round Reviews"
author: "Juliano Palacios Abrantes"
date: "17/05/2020"
output: pdf_document
bibliography: ../../../../References/Oceans_Canada_Biblio.bib
---

Recommendation Submitted by: David VanderZwaag
-----------------------------------------------------

 The authors have substantially addressed most of the reviewer comments
 but there are still some wording issues and more substantive issues that
 should be addressed. 

 Wording issues:

 Line 22...should read United Nations Law of the Sea Convention
 
 - We have addressed this comment

 Line 28...UNCLOS is binding international law. Do authors mean not a
 domestic law?
 
 - We originally meant to state that UNCLOS creates and incentive for states to cooperate but these are not oblige to do so. We note that this was confusing and have modified the sentence. It now reads:
 
*Under Article 63, UNCLOS incentives actions to cooperate on the management of shared stocks [@UnitedNations:1986tl] as often management success depends on effective cooperation between parties [@Munro:2002uf; @Sumaila:2013hv].*

Line 122...celebrate? Better wording might be...have used a.

- We have change the wording as suggested

 Line 125...where nor were. 
 
 - We have addressed this comment

 Line 350...wording needs correction...within across.
 
 - We have addressed this comment, it now reads:
 
*The potential adaptation of side payments in terms of quota swaps or allocating EEZ-fishing rights across the Gulf of Maine EEZs could be a potential solution as stocks shift due to climate change.*

 Line 377...Bering Sea not Berring Sea
 
 - We have addressed this comment

 There are quite a few past/present tense issues which will need to be
 corrected before publication.

- We have addressed this comment

 Substantive issues:

 1. A major problem still surrounds the treatment of NAFO in this paper
 and the proposition that NAFO involves joint
     Canada-USA management. NAFO only manages those stocks that are in the
 Regulatory Area ( high seas) and
     those that straddle the EEZs of coastal States and the high seas.
 While NAFO Convention zonal areas are used for domestic   
     management  purposes, NAFO does not manage fisheries within the EEZs
 of Canada and the United States. The NAFO website            
     presently only lists19 stocks and 11 species subject to NAFO
 management. Table 1 suggests 26 NAFO managed species and    
     also states that the Gulf of Maine Agreement (should be Arrangement)
 species are also managed by NAFO. That is not correct.
     If the NAFO treatment is retained in the paper, then the notion that
 the stock share ratio will only be a question between
     Canada and the United States needs to be reconsidered. There are 12
 Parties to the NAFO Convention. 
 
 - We thank the editor for pointing out this particular issue. We agree with the comment regarding the straddling nature of NAFO's stocks and decided to focus the paper on the two case studies. We believe the paper does not lose its main focus with this change as most of our discussion was already based on the IPHC and Gulf of Maine case studies. On the contrary, this change made the article more concise and on point. Moreover, the manuscript now aligns even more with other papers in the Special Feature (e.g Sumaila et al. uses the same species). We show here the specific changes of each section that are reflected in the manuscript:

Introduction. No changes.
 
Methods. Treaties table has been removed and the first paragraph now reads;
 
*The current study used the International Pacific Halibut Commission (IPHC) and the Gulf of Maine arrangement (hereafter referred as GoMA) as case studies to discuss the implications that climate change could have in the management of transboundary stocks. For the IPHC, we used the most updated spatial regulatory data along its 12 regulatory areas [@IPHCSecreatriat:2017uz; @IPHC:2019wt]. For this specific case, we considered Alaska as a separate entity, the US contiguous states as a second one (Washington, Oregon and California), and lastly British Columbia (Canada). For the GoMA we used the Northwest Atlantic Fisheries Organization's (NAFO) divisions 5Y, 5Ze, and 4X[^NAFO] within latitudes 46.2°N and 41.5°S, and longitudes -72°W and -64°E (Fig. 1). Is worth mention that, while NAFO's regulatory areas were used in this study for domestic management, NAFO does not manage fisheries within the EEZs of Canada and the United States. Fisheries data was gathered from the Sea Around Us from 1951 to 2014 [@Zeller2016].*
 
Results. The first section of the results referent to all species was removed along with Figure 1 and Table 1. Results now focus on each one of the case studies but no text was added.
 
Discussion. We only modified the first paragraph that now reads:
 
 *The results of the present study suggest that climate change will alter the MCP of jointly managed transboundary fish stocks in North America consequently altering Canada’s and the US’s species’ stock-share ratio, regardless of the climate change scenario. These results are aligned with regional [@Morley:2018fn] projections suggesting that climate change will push marine species towards the poles and deeper water [@Pinsky:2013jo] in search of their ecological niche [@Poloczanska:2016kk]. Moreover, IPHC data[^IPHC] suggest that some of these shits are already happening. For example, since 2010, the distribution proportion of Pacific halibut has increased from 9% to 11% in region 2B, from 7.5% to 13% in region 2C, and from 12.3% to 13.5% in region 4CDE. On the other hand, regions 3A and 3B have seen the largest decreases in the IPHC regulatory areas since 2010, from 35.3% to 30.6% and 20.6% to 15.9%, respectively. Similarly, in the Gulf of Maine, the projected stock-share gain of yellowtail flounder and haddock by the US (Fig. 5) follows a historical trend where in 2019, Canada's stock-share decreased from 35% to 32% and 60% to 40% relative to 2010, respectively [@Trinko:2019ou].*
 
 Conclusion. No change
 

 2. The paper might provide details on how the distributions of George's
 Bank stocks have actually been shifting or not since 2010 
     when the 90% distribution formula became fully operational. Anonymous
 reviewer A raised this point but it has not been 
     adequately addressed in my opinion.
     
- We expanded the current paragraph that touches in this matter. It reads in the discussion on line 301:

*By allocating quotas based on yearly surveys along the Convention area, the IPHC should be able to capture shifts in Pacific halibut distribution due to climate change, reducing the chances of over exploitation of the stock due to this shifts [@Miller:2013iv]. Similarly, for the Gulf of Maine, since the GoMA’s method to estimate quota allocation is weighted based on stocks distribution (90%) and historical catch (10%) [@TRAC:2016wu]. This process is especially important for cod and haddock due to their distribution variation within the Gulf [@Soboil:2006gw; @TRAC:2016wu]. However, since 2010, when the weighted method was implemented, the quota allocation has favored the US over Canada, especially in terms of haddock and yellowtail flounder [@Trinko:2019ou]. A perpetuation of this trend with no mitigation policy could jeopardize the arrangement as Canada's quota reduction could disincentive cooperation (see Sumaila et al., this Special Feature).*


References:
