---
title: "Second Round Reviews"
author: "Juliano Palacios Abrantes"
date: "17/05/2020"
output: pdf_document
---

Recommendation Submitted by: David VanderZwaag
-----------------------------------------------------

 The authors have substantially addressed most of the reviewer comments
 but there are still some wording issues and more substantive issues that
 should be addressed. 

 Wording issues:

 Line 22...should read United Nations Law of the Sea Convention
 
 - We have addressed this comment

 Line 28...UNCLOS is binding international law. Do authors mean not a
 domestic law?
 
 - We originally meant to state that UNCLOS incentivizes states to cooperate but these are not oblide to do so. We note that this was confusing and have modified the sentence. It now reads:
 
*Under Article 63, UNCLOS incentives actions to cooperate on the management of shared stocks [@UnitedNations:1986tl].*

 Line 122...celebrate? Better wording might be...have used a.

- We have change the wording as suggested

 Line 125...where nor were. 
 
 - We have addressed this comment

 Line 350...wording needs correction...within across.
 
 - We have addressed this comment, it now reads:
 
 *The potential adaptation of side payments in terms of quota swaps or allowing EEZ-fishing rights across the Gulf of Maine EEZs could be a potential solution as stocks shift due to climate change.*
 
 - We have addressed this comment

 Line 377...Bering Sea not Berring Sea
 
 - We have addressed this comment

 There are quite a few past/present tense issues which will need to be
 corrected before publication.

 Substantive issues:

 1. A major problem still surrounds the treatment of NAFO in this paper
 and the proposition that NAFO involves joint
     Canada-USA management. NAFO only manages those stocks that are in the
 Regulatory Area ( high seas) and
     those that straddle the EEZs of coastal States and the high seas.
 While NAFO Convention zonal areas are used for domestic   
     management  purposes, NAFO does not manage fisheries within the EEZs
 of Canada and the United States. The NAFO website            
     presently only lists19 stocks and 11 species subject to NAFO
 management. Table 1 suggests 26 NAFO managed species and    
     also states that the Gulf of Maine Agreement (should be Arrangement)
 species are also managed by NAFO. That is not correct.
     If the NAFO treatment is retained in the paper, then the notion that
 the stock share ratio will only be a question between
     Canada and the United States needs to be reconsidered. There are 12
 Parties to the NAFO Convention. 
 
 
 - We understand the concerns of the edditor and have made very clear that we do not imply that these fisheries are soley co-managed by Canada and the US but that bnecause they are part of NAFO they are, in nature, transboundary. It now reads in the methods section
 
**All species under the IPHC, Pacific Salmon Commission, the Pacific Whiting Treaty, and the GoMA arrangement were analyzed as these are bi-lateral agreements. However, in the case of NAFO, the Comission is signed by 12 members and oversees the managment of 11 species in areas beyong national jurisdicions. Within the EEZs, NAFOs areas are used for management purposes but the management of stocks is made by each conuntry, unless a bilateral arrangement exists. For the purpose of this study, we assume that 26 species reported in NAFO's catch statistics fished in regions that fall within the EEZs of Canada and the United States (NAFO subareas 2s, 3s with the exception of 3M and 3N and limited to the EEZ, 4s, 5s and 6 A,B, and C), were transboundary in ntarue.**
 
 Note that we have updated the table to read Gulf of Maine Arrangement.
 

 2. The paper might provide details on how the distributions of George's
 Bank stocks have actually been shifting or not since 2010 
     when the 90% distribution formula became fully operational. Anonymous
 reviewer A raised this point but it has not been 
     adequately addressed in my opinion.